In [9]:
import torch
from torchsummary import summary
from model import Unet_40k

In [10]:
model = Unet_40k(in_ch=4, out_ch=1)

In [15]:
model(torch.randn(40962, 4)).shape

[10249 10244 10242 ... 40719 39990 40961]
[10249 10244 10242 ... 40719 39990 40961]
[ 2569  2564  2562 ... 10161  9918 10241]
[ 2569  2564  2562 ... 10161  9918 10241]
[ 649  644  642 ... 2535 2454 2561]
[ 649  644  642 ... 2535 2454 2561]
[169 164 162 ... 633 606 641]
[169 164 162 ... 633 606 641]
[ 49  44  42 ... 159 150 161]
[ 49  44  42 ... 159 150 161]
[169 164 162 ... 633 606 641]
[169 164 162 ... 633 606 641]
[ 649  644  642 ... 2535 2454 2561]
[ 649  644  642 ... 2535 2454 2561]
[ 2569  2564  2562 ... 10161  9918 10241]
[ 2569  2564  2562 ... 10161  9918 10241]
[10249 10244 10242 ... 40719 39990 40961]
[10249 10244 10242 ... 40719 39990 40961]


torch.Size([40962, 1])